export const Constants = {
  EMAIL: "info@prostohttp.ru",
  SITE_URL: "http://localhost:3001/",
  IMG_MAIN: "img/",
  IMG_CATEGORIES: "img/categories/",
  IMG_PRODUCTS: "img/products/",
  IMG_BRANDS: "img/brands/",
  IMG_BANNERS: "img/banners/",
  IMG_OPTIONS: "img/options/",
  IMG_ARTICLES: "img/articles/",
  IMG_USERS: "img/users/",
  PER_PAGE_USERS: 18,
  PER_PAGE_PRODUCT: 9,
  PER_PAGE_SEARCH: 9,
  PER_PAGE_ORDER: 18,
  PER_PAGE_BRAND: 18,
  PER_PAGE_ARTICLE: 18,
  PER_PAGE_OPTION: 18,
  PER_PAGE_BANNERS: 18,
  PER_PAGE_CATEGORY: 18,
  NOTIFICATIONS_LIMIT: 4,
  SEARCH_LIMIT: 10,
  MAX_VISIBLE_IN_PAGINATION: 5,
  PROVIDE_IS_OPEN_MOBILE_SIDEBAR: "isOpenMobileSidebar",
  MAX_FILE_SIZE: 5000,
  fileTypes: {
    image: ["image/jpeg", "image/jpg", "image/png", "image/webp"],
  },
  STRING_MIN_LENGTH: 2,
  NUMBER_MIN_VALUE: 1,
};
