export const Constants = {
  EMAIL: "info@prostohttp.ru",
  SITE_URL: "http://localhost:3001",
  IMG_CATEGORIES: "img/categories/",
  IMG_PRODUCTS: "img/products/",
  IMG_BRANDS: "img/brands/",
  IMG_OPTIONS: "img/options/",
  IMG_ARTICLES: "img/articles/",
  IMG_USERS: "img/users/",
  PER_PAGE_CAT: 8,
  PER_PAGE_PROD: 12,
  PER_PAGE_ORDER: 10,
  PER_PAGE_BRAND: 20,
  PER_PAGE_ARTICLE: 10,
  NOTIFICATIONS_LIMIT: 3,
};
