export const Constants = {
  EMAIL: "info@prostohttp.ru",
  SITE_URL: "http://localhost:3001/",
  IMG_CATEGORIES: "img/categories/",
  IMG_PRODUCTS: "img/products/",
  IMG_BRANDS: "img/brands/",
  IMG_OPTIONS: "img/options/",
  IMG_ARTICLES: "img/articles/",
  IMG_USERS: "img/users/",
  PER_PAGE_USERS: 6,
  PER_PAGE_PROD: 6,
  PER_PAGE_ORDER: 6,
  PER_PAGE_BRAND: 6,
  PER_PAGE_ARTICLE: 6,
  PER_PAGE_CATEGORY: 6,
  NOTIFICATIONS_LIMIT: 4,
  SEARCH_LIMIT: 10,
  MAX_VISIBLE_IN_PAGINATION: 5,
  PROVIDE_IS_OPEN_MOBILE_SIDEBAR: "isOpenMobileSidebar",
  MAX_FILE_SIZE: 5000,
  fileTypes: {
    image: ["image/jpeg", "image/jpg", "image/png", "image/webp"],
  },
};
